### ISSUE TITLE
[Question] In micro_controller, about the shape of params

### ISSUE THREAD

**Issue by yukang2017** [melodyguan/enas#20]
Thank you for your code.

https://github.com/melodyguan/enas/blob/2734eb2657847f090e1bc5c51c2b9cbf0be51887/src/cifar10/micro_controller.py#L178

This line of code is supposed to decide the type of op (e.g. conv 3x3 or 5x5). But the shape of **self.w_soft**, **self.b_soft** is **[self.lstm_size, self.num_branches]** and **[1, self.num_branches]**.

I think they should be  **[self.lstm_size, self.num_type_ops]** and **[1, self.num_type_ops]** ?

**Comment by hyhieu** [comment]
In our code, `num_branches` is the class variable that means number of possible operations, which is `num_type_ops` in your understanding.
