### ISSUE TITLE
 Executor failed to create kernel

### ISSUE THREAD

**Issue by zswartz1993** [melodyguan/enas#25]
I am attempting to run the macro search on the cifar10 dataset and am getting the error:
"Executor failed to create kernel. Invalid argument: Default AvgPoolingOp only supports NHWC."
...
...
...
"InvalidArgumentError (see above for traceback): Default AvgPoolingOp only supports NHWC.
         [[Node: child/layer_3/pool_at_3/from_0/AvgPool = AvgPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], _device="/job:localhost/replica:0/task$"

Any Ideas? The cifar10 data is in its original format. I am running this on GCP currently, but got the error on my local VM as well. I am using tensorflow 1.4.

**Comment by hyhieu** [comment]
You seem to be running your graph on a CPU instead of the GPU. We got this problem when we made that mistake too, as CPUs don't support the `NHWC` format.
