### ISSUE TITLE
Why can we get different sample_arcs with a fixed controller?

### ISSUE THREAD

**Issue by flymark2010** [melodyguan/enas#28]
In your code , when the controller has been trained,  you samples 10 architectures and they are all different. In my understanding, at this phase, the controller is fixed, and the inputs are all the same, then why can we get different sample_arcs?

**Comment by yukang2017** [comment]
Randomly initialize the first input to RNN controller? I guess.

Do you have any idea?

**Comment by flymark2010** [comment]
I think the input is fixed, but the action is sampled from a multinomial distribution. Code [here](https://github.com/melodyguan/enas/blob/master/src/cifar10/micro_controller.py#L162).
