### ISSUE TITLE
Compatibility Issues 

### ISSUE THREAD

**Issue by zswartz1993** [melodyguan/enas#30]
Hello,

I've been experiencing difficulties trying to get tensorflow-gpu 1.4 to work with my setup. Which OS, CUDA toolkit version, and CUDNN version are you using? I've attempted to do this on GCP as well as my local machines.

**Comment by hyhieu** [comment]
We developed on

- Ubuntu 16.04
- TF 1.4
- Python 2.7
- CUDA 8.0
- CuDNN 5.0

We are in the progress of upgrading to TF 1.7 and other settings. We'll soon push an update that's more version agnostic.
