### ISSUE TITLE
A question about micro child model

### ISSUE THREAD

**Issue by b-liu14** [melodyguan/enas#48]
In the following line, why use layers = [layers[-1], x] instead of layers = [layers[0], x]?

https://github.com/melodyguan/enas/blob/d1a90ac915301198f2a30ce136e9040e6c4235ff/src/cifar10/micro_child.py#L277

In my opinion, if use your implementation, the model in the search stage is very different from that in the final stage.

**Comment by MarkAlive** [comment]
I changed `[layers[-1], x]` to `[layers[0], x]` and get a better result.
