### ISSUE TITLE
Why use layer base?

### ISSUE THREAD

**Issue by b-liu14** [melodyguan/enas#49]
I notice that layer base is used in the final stage but no in the search stage. Can you explain why you use this? Thanks very much.

https://github.com/melodyguan/enas/blob/d1a90ac915301198f2a30ce136e9040e6c4235ff/src/cifar10/micro_child.py#L416

**Comment by Ian09** [comment]
Hi @b-liu14 
I have the same question, do you know the reason why to use layer_base? BTW, it seems the minor_search is inconsistent with minor_final, it is really weird...

**Comment by b-liu14** [comment]
Sorry, I don't know the reason. Maybe it's just a dark magic. 
I close the issues because the authors don't reply for a long time.
