### ISSUE TITLE
About micro search running on multi GPUs

### ISSUE THREAD

**Issue by ChrisMii** [melodyguan/enas#60]
I am trying to modify the code and make it run on multi GPUs, but it shows that the speed(time_per_epoch/(num_gpu*batch_size)) on two gpus is the same as on the single gpu, which means it didnt accerlarate at all.And I try more on three and four gpus, I get the 1x speed and 1.5x speed. here is what i do about the code:
1:in mirco_child->_bulid_train: I use loop to put the data into model on every gpu for num_gpu times, (every loop I call train.shuffle_batch to get data) and put the loss on every gpu into collections.
 2:Then in get_train_ops, I use tower, get the loss in 1st step and add the l2 loss. Then calculate the gradients on every gpu and average them on cpu.
any one can help me?

**Comment by s9xie** [comment]
@ChrisMii Hi ChrisMii. I recently tried multigpu training as well and saw similar problem (no speedup for child training with 2 gpus) as you described. Did you solve the issue? Thanks!

**Comment by marsggbo** [comment]
Can you show your code?
