### ISSUE TITLE
What is the parameter "search_whole_channels" in class GeneralController mean ?

### ISSUE THREAD

**Issue by svjack** [melodyguan/enas#81]
When setting search_whole_channels as true, the sample "tf.multinomial" process only 
call single time in one iter of for loop which seemed like common policy gradient calculate process.
But when set to False (as default) call two times,
1) the first time, sample "start" from whole distribution.
2) use mask to mapping distribution whose elements less_equal than out_filters - start - 1 
    to 0 probs

It seems that the order in 2) is "cross" with 1) i.e. start, what is that mean ?
What is "count" mean ?
Does it  correspond to the params in general_child.py and only the self-defining sample criterion. 
Or it has some special meaning that can interpret with paper contents ?

And the following calculate process sum entropys from 1) and 2) together, without distinguish.
Why ?

And what is the difference between "MicroController" and "GeneralController" 
the former not has above process.

I also take a glance at a pytorch implementation in 
https://github.com/carpedm20/ENAS-pytorch
It's controller's sample process only sample one time as 1) 
but not have "count",  what is the difference ?

I think i may get the answer.

**Comment by CanyonWind** [comment]
Hi @svjack , I think I have the same question here. Do you mind sharing your interpretation? Thanks!
